### ISSUE TITLE
Add JWT authorization to EnvironmentVariableProvider

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe-http-worker#20]
Example from legacy code: https://github.com/camunda-cloud/zeebe-http-worker/compare/cep004_auth_for_http-worker

Three environment variables that will be set:
* AUTH0_BASE_URL <- der endpunkt von dem man die jwt tokens beziehen kann
* AUTH0_CLIENT_ID <- die client Id fuer den spezifischen worker
* AUTH0_CLIENT_SECRET <- das dazugehoerige secret
* AUTH0_AUDIENCE < (e.g. variableEndpointAudience = process.env.ENV_VARS_URL.replace('https://', '').split(':')[0]; //variables.cloud.dev.ultrawombat.com )

Needs to go into https://github.com/zeebe-io/zeebe-http-worker/blob/master/src/main/java/io/zeebe/http/EnvironmentVariableProvider.java

**Comment by ColRad** [comment]
So basically you need to `POST` to `AUTH0_BASE_URL` with an JSON payload of
`{
      client_id: AUTH0_CLIENT_ID,
      client_secret: AUTH0_CLIENT_SECRET,
      audience: AUTH0_AUDIENCE,
      grant_type: 'client_credentials'
}`

This call returns something like this:
`{
    token_type: 'Bearer',
    access_token: JWT_ACCESS_TOKEN
}`

When you have the token, insert it in the Authorization Header: 
Header: `Authorization: Bearer JWT_ACCESS_TOKEN`

cache the token, so you dont need to re-request it.

When the token gets invalid, expect an 401 or 403. 
Then just re-request the token.

**Comment by ColRad** [comment]
To decouple from the name 'Auth0' we decided to rename all the AUTH0_ env vars to:
`AUTH0_BASE_URL` -> `M2M_BASE_URL`
`AUTH0_CLIENT_ID` -> `M2M_CLIENT_ID`
`AUTH0_CLIENT_SECRET` -> `M2M_CLIENT_SECRET`

and we add an env var `M2M_AUDIENCE` so http-worker implementer dont need to Edward Scissorhands the ENV_VARS_URL

**Comment by berndruecker** [comment]
@ColRad Would you mind renaming them even to

**Comment by ColRad** [comment]
ok will do
