### ISSUE TITLE
Variables format from ENV_VARS_URL is wrong

### ISSUE THREAD

**Issue by ColRad** [zeebe-io/zeebe-http-worker#24]
The endpoint returns an JSON Array with following format: 

`[{ key: 'testKey0', value: 'testValue0' }, { key: 'testKey1', value: 'testValue1' }]`

**Comment by berndruecker** [comment]
See https://github.com/camunda-cloud/console/blob/master/commons/WorkerVariable.dto.ts in legacy cloud worker
