### ISSUE TITLE
Not connecting to zeebe inside a cloud Zeebe cluster

### ISSUE THREAD

**Issue by ColRad** [zeebe-io/zeebe-http-worker#25]
To connect to a zeebe gateway inside the same namespace (Cloud Zeebe cluster) the env var ZEEBE_GATEWAY_ADDRESS can be used.

**Comment by berndruecker** [comment]
@ColRad Can you please adjust the environment variable when using the new docker image? The current value is the default used at different places in the Zeebe ecosystem, so we need to keep it (and it is quite a bit of effort to allow to an alias)

**Comment by ColRad** [comment]
ok will do, is `ZEEBE_ENDPOINT` ok?

**Comment by berndruecker** [comment]
No - please use the one defined in https://github.com/camunda-cloud/zeebe-http-worker/issues/38

zeebe.client.broker.contactPoint=127.0.0.1:26500

**Comment by ColRad** [comment]
ok will do

**Comment by ultraschuppi** [comment]
let us go with `ZEEBE_CLIENT_BROKER_CONTACTPOINT`

**Comment by berndruecker** [comment]
Yeah - sorry - I fix the docs
