### ISSUE TITLE
Liveliness probe not working.

### ISSUE THREAD

**Issue by ColRad** [zeebe-io/zeebe-http-worker#26]
Probe should be available under
`/healthz`

**Comment by berndruecker** [comment]
@ColRad  Couldn't you change the probe URL? The current URL is Spring Boot default and thus I would love to keep it.

**Comment by ColRad** [comment]
@berndruecker does spring serve an `/actuator/ready` endpoint as well? We need this for k8s monitoring.

**Comment by berndruecker** [comment]
Currently there is the same endpoint serving this - please use that one for both.
We briefly started the discussion but abandoned it if there is value in a special health endpoiint, as e.g. a lost connection to Zeebe does not make the Http Worker unhealthy. So spontaneously I don#t know what exactly would make it unhealthy that is different from ready

**Comment by ColRad** [comment]
ok will just use the `/actuator/health`
