### ISSUE TITLE
The HTTP Worker needs to access Zeebe Job data

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe-http-worker#3]
In some cases the HTTP Worker needs to able to pass on information about the current job, at least the job id (which is required to correlate later on). 
This should be supported via expression language.

Maybe it is already possible, then just double check and document it :-)

**Comment by saig0** [comment]
Thank you for raising this up. In which way should this information be available?

Do you have any concrete examples? Please share :)

**Comment by berndruecker** [comment]
See the use case mentioned in https://github.com/zeebe-io/zeebe-http-worker/issues/4

**Comment by berndruecker** [comment]
Currently I would assume that we should limit the amount of data available, as this might potentially change later on when we have expressions in the broker itself (which I think could support something like "workflowInstance.id":

- Resolve ```jobKey``` to the current job.getKey()
- Resolve ```workflowInstanceKey``` to the current job.getWorkflowInstanceKey()

**Comment by saig0** [comment]
`jobKey` and `workflowInstanceKey` are exposed and can be used in placeholders (e.g. `/url/{{jobKey}}`) e54c3fc325260c4862a762415b6da121e901710a
