### ISSUE TITLE
Inconsistent order of variable preference in ConfigurationMaps.java

### ISSUE THREAD

**Issue by 0x15e** [zeebe-io/zeebe-http-worker#33]
It looks like there are effectively two ways to retrieve the configuration for a job via the ConfigurationMaps class: the `get` (or `getString`) or `getConfig` methods.

However, the custom headers, job variables, and environment variables are added to the config map in a different order than they are referenced by the `get` method.

For example, if a job has a custom header "foo" with value "foo" _and also_ a variable "foo" with value "bar", a call to `get` or `getString` will return "foo" while using `getConfig` and then retrieving "foo" from the config will result in a value of "bar".

[Here is the code in question.](https://github.com/zeebe-io/zeebe-http-worker/blob/86e4ddafe41335bf71291eb9bef2402a403d11db/src/main/java/io/zeebe/http/ConfigurationMaps.java#L32-L58) 

What is the intended order of preference for these variables?

**Comment by berndruecker** [comment]
I am not sure if there was a special reasoning for that decision (maybe @saig0 remembers), but I do agree that this is confusing and we should harmonize the behavior. I plan to do another iteration on the worker next week.

**Comment by saig0** [comment]
Agree. That does not make much sense. I should be consistent ;)

**Comment by berndruecker** [comment]
I plan to release a 0.22.0 version of the worker soon where this is resolved

**Comment by 0x15e** [comment]
Thanks for clearing it up!
