### ISSUE TITLE
503 response causes halt

### ISSUE THREAD

**Issue by jwulf** [zeebe-io/zeebe-http-worker#49]
If the HTTP Worker gets a 503, it doesn't raise an incident or return an error. The process just halts.

<img width="596" alt="Screen Shot 2020-02-13 at 5 01 51 pm" src="https://user-images.githubusercontent.com/406975/74409994-c457eb80-4e83-11ea-950e-35e835187a38.png">
<img width="319" alt="Screen Shot 2020-02-13 at 5 05 28 pm" src="https://user-images.githubusercontent.com/406975/74409998-c6ba4580-4e83-11ea-9318-01c39afa98fe.png">
<img width="394" alt="Screen Shot 2020-02-13 at 5 06 14 pm" src="https://user-images.githubusercontent.com/406975/74410011-ccb02680-4e83-11ea-95a1-0b2c472c52e5.png">
<img width="895" alt="Screen Shot 2020-02-13 at 5 06 37 pm" src="https://user-images.githubusercontent.com/406975/74410021-d20d7100-4e83-11ea-9684-c03a26d52c52.png">

**Comment by saig0** [comment]
Should be fixed by #69.
