### ISSUE TITLE
Add Docker build which can be used also within Camunda Cloud

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe-http-worker#6]
Simple Docker file, comparable to the current Cloud Worker: https://github.com/camunda-cloud/zeebe-http-worker/blob/master/Dockerfile

**Comment by berndruecker** [comment]
See also https://github.com/zeebe-io/zeebe-http-worker/tree/master/.ci to create a build on Jenkins

**Comment by berndruecker** [comment]
Still need to do the CI stuff

**Comment by menski** [comment]
Added to CI with cf309f5a64d97d7a4492c7f69e75163892ffb315
